### ISSUE TITLE
.net core 3.1 使用autofac结合aspectcore builder.RegisterDynamicProxy() 报错

### ISSUE THREAD

**Issue by lovredo** [dotnetcore/AspectCore-Framework#209]
引用 AspectCore.Extensions.Autofac 2.0.0，Autofac.Extensions.DependencyInjection 6.0.0

在.net core 3.1 使用autofac结合aspectcore时，builder.RegisterDynamicProxy() 
编译报错：Method not found: 'Autofac.Builder.DeferredCallback Autofac.ContainerBuilder.RegisterCallback(System.Action`1<Autofac.Core.IComponentRegistry>)'.

stacktrace:
at AspectCore.Extensions.Autofac.ContainerBuilderExtensions.RegisterDynamicProxy(ContainerBuilder containerBuilder, IAspectConfiguration configuration, Action`1 configure)
   at AspectCore.Extensions.Autofac.ContainerBuilderExtensions.RegisterDynamicProxy(ContainerBuilder containerBuilder, Action`1 configure)
   at Summer.WebApi.Startup.ConfigureContainer(ContainerBuilder builder) in D:\work\leon\SummerCore3.1\Summer.WebApi\Startup.cs:line 150
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureContainerBuilder.InvokeCore(Object instance, Object container)
   at Microsoft.AspNetCore.Hosting.ConfigureContainerBuilder.<>c__DisplayClass10_0.<Invoke>g__StartupConfigureContainer|0(Object containerBuilder)
   at Microsoft.AspNetCore.Hosting.ConfigureContainerBuilder.Invoke(Object instance, Object container)
   at Microsoft.AspNetCore.Hosting.ConfigureContainerBuilder.<>c__DisplayClass8_0.<Build>b__0(Object container)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.ConfigureContainer[TContainer](HostBuilderContext context, TContainer container)
   at Microsoft.Extensions.Hosting.Internal.ConfigureContainerAdapter`1.ConfigureContainer(HostBuilderContext hostContext, Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Summer.WebApi.Program.Main(String[] args) in D:\work\leon\SummerCore3.1\Summer.WebApi\Program.cs:line 17

**Comment by nivalxer** [comment]
Autofac不要使用5.0的版本。最新代码已经支持，还未发布版本。也可以自己下载编译后使用。

**Comment by nivalxer** [comment]
新版本已发布了，试试应该没问题了

**Comment by huoshan12345** [comment]
请升级到2.1.0+的版本再试试如果有问题再重开

**Comment by landonzeng** [comment]
目前项目是core 3.1，使用最新版的autofac还是报上面的错误

**Comment by landonzeng** [comment]
> 新版本已发布了，试试应该没问题了

目前项目是core 3.1，使用最新版的autofac还是报上面的错误

**Comment by nivalxer** [comment]
> > 新版本已发布了，试试应该没问题了
> 
> 目前项目是core 3.1，使用最新版的autofac还是报上面的错误

AspectCore使用最新版本+Autofac最新是可以正常使用的，检查一下包版本看看。

**Comment by landonzeng** [comment]
> AspectCore使用最新版本+Autofac最新是可以正常使用的，检查一下包版本看看。

netcore 是3.1 的，Autofac 是5.2.0的

**Comment by nivalxer** [comment]
> > AspectCore使用最新版本+Autofac最新是可以正常使用的，检查一下包版本看看。
> 
> netcore 是3.1 的，Autofac 是5.2.0的
> 
> ![QQ截图20200617111140](https://user-images.githubusercontent.com/7336781/84851086-fd030e00-b08b-11ea-89b8-ed63443cc639.png)
> ![QQ截图20200617111204](https://user-images.githubusercontent.com/7336781/84851090-fffdfe80-b08b-11ea-9eb6-e87b36506671.png)

没有看到你的AspectCore版本，请确认是否更新到了2.1.0+

![image](https://user-images.githubusercontent.com/6287552/84861165-051a7800-b0a3-11ea-94f5-500200f9dfcb.png)
