### ISSUE TITLE
.NetCore3.1 配合Autofac5.2 异常

### ISSUE THREAD

**Issue by QQ897878763** [dotnetcore/AspectCore-Framework#231]
在Startup下的Configure方法内执行 app.ApplicationServices.GetAutofacRoot() 代码获取ILifetimeScope容器对象时候出现如下异常：
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to retrieve Autofac root lifetime scope from service provider of type AspectCore.Extensions.Autofac.AutofacServiceResolver.
  Source=Autofac.Extensions.DependencyInjection
  StackTrace:
   at Autofac.Extensions.DependencyInjection.ServiceProviderExtensions.GetAutofacRoot(IServiceProvider serviceProvider)
   at SunYa.ITFS.WebApi.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in D:\Code\SunYa\VS2019\SunYa.Imds.Import\src\SunYa.ITFS.WebApi\SunYa.ITFS.WebApi\Startup.cs:line 141
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()

Unable to retrieve Autofac root lifetime scope from service provider of type AspectCore.Extensions.Autofac.AutofacServiceResolver.

System.InvalidCastException:“Unable to cast object of type 'Microsoft.Extensions.DependencyInjection.ServiceCollection' to type 'Autofac.ContainerBuilder'.”
```

引用的AspectCore以及Atuofac相关包信息如下：
![image](https://user-images.githubusercontent.com/15921032/93555980-23e22080-f9aa-11ea-9daa-dbd8d50f9b8d.png)

Startup代码注册AOP如下：
```
  public void ConfigureContainer(ContainerBuilder builder)
  {
            //注册动态代理的接口和相关拦截器配置
            builder.RegisterDynamicProxy(config =>
            {
                config.Interceptors.AddServiced<ImportReportInterceptorAttribute>();
            });
            builder.RegisterModule(new AutofacModule(Configuration));                  
 }
```
Program代码如下:
```
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
                  Host.CreateDefaultBuilder(args)
                  .ConfigureLogging(log =>
                  {
                      log.ClearProviders();
                      log.SetMinimumLevel(LogLevel.Trace);
                  }) //DynamicProxyServiceProviderFactory
                  .UseServiceProviderFactory(new AutofacServiceProviderFactory())  
                      .ConfigureWebHostDefaults(webBuilder =>
                      {
                          webBuilder.UseStartup<Startup>();
                      }).UseNLog();
    }
```
经本人测试，只要移除Startup下的ConfigureContainer方法内注册AOP的代码块就不会报错了，但是这样的话AspectCore就没作用了，所有的切面特性类里代码都不会执行了

**Comment by QQ897878763** [comment]
。。。。找到了解决问题的方法，需要更新Startup.cs文件内的Configure代码
before：
```
// 直接使用app.ApplicationServices.GetAutofacRoot()获取ioc容器
ContainerManager.Current.Container = app.ApplicationServices.GetAutofacRoot();
```
// after
```
// 采取app.ApplicationServices.CreateScope().ServiceProvider.GetAutofacRoot()获取
ContainerManager.Current.Container = app.ApplicationServices.CreateScope().ServiceProvider.GetAutofacRoot();
```
代码参考https://github.com/levy-w-wang/Demo.Ioc_Aop
