### ISSUE TITLE
AspectCore.Extensions.DependencyInjection 中InterceptorCollector 作用域问题

### ISSUE THREAD

**Issue by yjqGitHub** [dotnetcore/AspectCore-Framework#281]
您好，我们看代码中发现以下实例生命周期作用域有冲突：
![8CD90A40-5829-4115-B1AF-F498907CA037](https://user-images.githubusercontent.com/15052182/158318464-06542ace-b056-4dc6-94d2-0c0e0f2fb58f.png)
![73341964-9964-471b-B776-AE3191E47837](https://user-images.githubusercontent.com/15052182/158318631-efecb164-1446-4dad-b1d4-09b0fa74033c.png)
IPropertyInjectorFactory 接口是Scope作用域，但是InterceptorCollector作用域是Singleton单例，InterceptorCollector中引用了IPropertyInjectorFactory ，也就是在Singleton的实例中引用了Scope，这个设计是不是不合理的？
`System.InvalidOperationException: Cannot consume scoped service 'AspectCore.DependencyInjection.IPropertyInjectorFactory' from singleton 'AspectCore.DynamicProxy.IInterceptorCollector'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScopeCache(ServiceCallSite scopedCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)`

**Comment by liuhaoyang** [comment]
感谢指正 。 PropertyInjectorFactory 使用单例其实是没问题的

**Comment by latte-gh** [comment]
Closed: Fixed in PR #336. IInterceptorCollector and IAspectBuilderFactory registration changed from Singleton to Scoped in the MSDI path, resolving the scope isolation issue.
