### ISSUE TITLE
和Scrutor一起使用的問題

### ISSUE THREAD

**Issue by frank58246** [dotnetcore/AspectCore-Framework#286]
你好，想要请教一下
我在.net core专案中
使用Scutor套件做装饰者模式的DI
套用之后
就无法被AspectCore的属性拦截生成Proxy的class
想问你们有遇到过类似的问题吗
谢谢
專案連結 https://github.com/frank58246/AOE_Test
![未命名](https://user-images.githubusercontent.com/3856292/179384689-be58d8ce-2e13-4da3-8f39-df9fbb2248cb.png)
![未命名1 1](https://user-images.githubusercontent.com/3856292/179384692-f4b2419a-00e2-46da-b5dd-1843b585b934.png)
![未命名1](https://user-images.githubusercontent.com/3856292/179384693-e80e5207-2eb9-417c-9b6b-783a17c702df.png)
![未命名2](https://user-images.githubusercontent.com/3856292/179384694-7bb32d43-c1f3-40c1-93d8-bd826780a07f.png)

**Comment by panosru** [comment]
I have the same issue as frank mentioned.

In addition, if  you try to use `DynamicProxyServiceProviderFactory` with `services.Decorate<>()` method that is provided by Scrutor like so:

![image](https://user-images.githubusercontent.com/400362/183240453-e3c0ba0a-3cbc-43df-8ec5-2a879b77e06d.png)

You'll be getting the following exception:

```
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at System.Reflection.MemberInfo.GetCustomAttributesData()
   at System.Reflection.MemberInfo.get_CustomAttributes()
   at AspectCore.Extensions.Reflection.MemberReflector`1..ctor(TMemberInfo reflectionInfo)
   at AspectCore.Extensions.Reflection.TypeReflector..ctor(TypeInfo typeInfo)
   at AspectCore.Extensions.Reflection.TypeReflector.<>c.<Create>b__0_0(TypeInfo info)
   at AspectCore.Extensions.Reflection.ReflectorCacheUtils`2.<>c__DisplayClass1_0.<GetOrAdd>b__0(TMemberInfo k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AspectCore.Extensions.Reflection.TypeReflector.Create(TypeInfo typeInfo)
   at AspectCore.Extensions.Reflection.ReflectorExtensions.GetReflector(TypeInfo typeInfo)
   at AspectCore.DynamicProxy.ReflectionUtils.IsNonAspect(TypeInfo typeInfo)
   at AspectCore.Extensions.DependencyInjection.ServiceValidator.TryValidate(ServiceDescriptor descriptor, Type& implementationType)
   at AspectCore.Extensions.DependencyInjection.ServiceCollectionBuildExtensions.WeaveDynamicProxyService(IServiceCollection services)
   at AspectCore.Extensions.DependencyInjection.ServiceCollectionBuildExtensions.BuildDynamicProxyProvider(IServiceCollection services)
   at AspectCore.Extensions.DependencyInjection.DynamicProxyServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in /Volumes/Projects/RND/VisualStudio/Demo/AOPDemo/Program.cs:line 24
```

Debug output:
![image](https://user-images.githubusercontent.com/400362/183240541-e7dc55fe-dab9-44dc-8138-6762d5da34f7.png)

**Comment by KittyChen913** [comment]
I also encounter the same error, and this issue continues to occur until now.
`'System.NotImplementedException: 'The method or operation is not implemented.'`

**Comment by james-jhang** [comment]
Hello guys, I had the same problem when using AspectCore and Scrutor. It turns out that the older version of Scrutor seems to be incompatible with AspectCore. When I upgrade Scrutor from 4.2.2 to 6.1.0, the problem is solved. Hope this will help you.

**Comment by latte-gh** [comment]
Closed: Scrutor's decorator registration pattern (DecorateWithImplementation) conflicts with proxy generation timing. This is a third-party compatibility issue. Consider using AspectCore's native interceptor attributes instead of Scrutor decorators for AOP scenarios.
