### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: This service descriptor is keyed. Your service provider may not support keyed services.

### ISSUE THREAD

**Issue by PawelTroka** [dotnetcore/AspectCore-Framework#326]
Code:

```
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args)
    {
        return Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); })
            .UseServiceContext();
    }
}
```

Stacktrace:
```
Unhandled exception. System.InvalidOperationException: This service descriptor is keyed. Your service provider may not support keyed services.
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.ThrowKeyedDescriptor()
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.get_ImplementationType()
   at AspectCore.Extensions.DependencyInjection.ServiceCollectionToServiceContextExtensions.Replace(ServiceDescriptor descriptor)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AspectCore.DependencyInjection.ServiceContext..ctor(IEnumerable`1 services, IAspectConfiguration aspectConfiguration)
   at AspectCore.DependencyInjection.ServiceContext..ctor(IEnumerable`1 services)
   at AspectCore.Extensions.DependencyInjection.ServiceCollectionToServiceContextExtensions.ToServiceContext(IServiceCollection services)
   at AspectCore.Extensions.DependencyInjection.ServiceContextProviderFactory.CreateBuilder(IServiceCollection services)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateBuilder(IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Neutral.Rfq.Api.Program.Main(String[] args) in Program.cs:line 11
```

**Comment by fivecky** [comment]
I'm having the same problem.

**Comment by liuhaoyang** [comment]
这个问题是因为 .NET 8 的 KeyedService 支持还未完全实现。PR #318 已经合并，但只添加了接口框架，实际的 GetKeyedService/GetRequiredKeyedService 方法还没有实现。

目前有以下几种解决方案：

**临时方案 1：避免使用 KeyedService**
如果你的项目可以调整，暂时使用非 Keyed 的服务注册方式。

**临时方案 2：降级到 .NET 7**
如果不强依赖 .NET 8 的特性，可以暂时降级到 .NET 7。

**正式修复**
KeyedService 的完整支持正在开发中，预计会在下一个版本中发布。你可以关注 issue #317 获取最新进展。
