### ISSUE TITLE
FormatException: Encountered an invalid type for a default value.

### ISSUE THREAD

**Issue by ZeekoZhu** [dotnetcore/AspectCore-Framework#96]
**Details:**

```
System.FormatException: Encountered an invalid type for a default value.

   at System.Reflection.MdConstant.GetValue(MetadataImport scope, Int32 token, RuntimeTypeHandle fieldTypeHandle, Boolean raw)

   at System.Reflection.RuntimeParameterInfo.GetDefaultValueInternal(Boolean raw)

   at System.Reflection.RuntimeParameterInfo.get_HasDefaultValue()

   at AspectCore.Utils.ProxyGeneratorUtils.ParameterBuilderUtils.DefineParameters(MethodInfo targetMethod, MethodBuilder methodBuilder)

   at AspectCore.Utils.ProxyGeneratorUtils.MethodBuilderUtils.DefineMethod(MethodInfo method, String name, MethodAttributes attributes, Type implType, TypeDesc typeDesc)

   at AspectCore.Utils.ProxyGeneratorUtils.MethodBuilderUtils.DefineInterfaceMethod(MethodInfo method, Type implType, TypeDesc typeDesc)

   at AspectCore.Utils.ProxyGeneratorUtils.MethodBuilderUtils.DefineInterfaceProxyMethods(Type interfaceType, Type targetType, Type[] additionalInterfaces, TypeDesc typeDesc)

   at AspectCore.Utils.ProxyGeneratorUtils.CreateInterfaceProxyInternal(String name, Type interfaceType, Type implType, Type[] additionalInterfaces, IAspectValidator aspectValidator)

   at AspectCore.Utils.ProxyGeneratorUtils.CreateInterfaceProxy(Type interfaceType, Type implType, Type[] additionalInterfaces, IAspectValidator aspectValidator)

   at AspectCore.DynamicProxy.ProxyTypeGenerator.CreateInterfaceProxyType(Type serviceType, Type implementationType)

   at AspectCore.Extensions.DependencyInjection.ServiceCollectionBuildExtensions.MakeProxyService(ServiceDescriptor descriptor, Type implementationType, IProxyTypeGenerator proxyTypeGenerator)

   at AspectCore.Extensions.DependencyInjection.ServiceCollectionBuildExtensions.BuildAspectCoreServiceProvider(IServiceCollection services)

```

**My Code:**

```
// ServiceAccessLogAttribute

public class ServiceAccessLogAttribute : AbstractInterceptorAttribute
    {
        public override async Task Invoke(AspectContext context, AspectDelegate next)
        {
            await next(context);
        }
    }
```

```
// Startup.ConfigureServices

services.AddTransient(provider => new ServiceAccessLogAttribute());
            services.AddDynamicProxy(config =>
            {
                config.Interceptors.AddServiced<ServiceAccessLogAttribute>(method =>
                {
                    var isService = method.DeclaringType.Name.EndsWith("Service");
                    return isService;
                });
            });
            return services.BuildAspectCoreServiceProvider();
```

**Project Info:**
```
OS: Windows 10
dotnet --version: 2.1.104
Target: netcoreapp2.0
AspectCore.Extensions.DependencyInjection: 0.3.1
```

**Comment by liuhaoyang** [comment]
麻烦再提供一下被拦截的函数

**Comment by ZeekoZhu** [comment]
在 Startup 阶段就挂了：

```
return services.BuildAspectCoreServiceProvider(); // <---- Exception!!!
```

拦截的函数大多是这种：

![image](https://user-images.githubusercontent.com/13861843/38479015-271941be-3bef-11e8-850d-7af151cee004.png)

**Comment by liuhaoyang** [comment]
此问题我在测试中并没有复现。

**Comment by startewho** [comment]
我的问题和楼上一样,也是在BuildAspectCoreServiceProvider出错了。返回的错误信息也一样。
